name: Mirror to Codeberg

on:
  push:
    branches: [ "main", "master" ] # 当主分支有更新时触发
  workflow_dispatch: # 允许手动点击按钮触发同步

jobs:
  codeberg-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror to Codeberg
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/${{ github.repository }}.git"
          source_branch: "refs/heads/*"
          destination_repo: "ssh://git@codeberg.org/MeidoPromotionAssociation/MeidoSerialization.git"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.CODEBERG_SSH_KEY }}
